name: Terraform workflow

on:
  workflow_dispatch:
    inputs:
      AWS_service:
        description: 'select the service for which you want to create the infra '
        required: true
        type: choice
        options:
        - ECS
        - cognito

      Infra_env:
        description: 'Name of the environment for which you want to create the infra'
        required: true
        type: choice
        options:
        - dev
        - uat
        - prod

      Operations:
        description: 'Select whether you want to create or destroy the infrastructure'
        required: true
        type: choice
        options:
        - create
        - destroy
        
env: 
      AWS_DEFAULT_REGION : us-east-1

jobs:
  
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: terraform-plan-for-create
        if: ${{ inputs.Operations }} == 'create'
        #working-directory: ./${{ inputs.AWS_service }}/${{ inputs.Infra_env }}
        run: |
            sh "cd ./ecs/dev"
            sh "terraform init"
            sh "terraform plan"

      # - name: review-and-approve-and-terraform-apply
      #   if: ${{ inputs.Operations }} == 'create' && github.ref_name == github.event.repository.default_branch
      #   working-directory: ./${{ inputs.AWS_service }}/${{ inputs.Infra_env }}
      - uses: trstringer/manual-approval@v1
        with: 
          approvers: sahilj713
          minimum-approvals: 1
          issue-title: "Have you reviewed the terraform plan for changes? Do you want to proceed with it?"
          issue-body: "Please approve or deny"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
        
      - name: terraform-apply
        if: ${{ inputs.Operations }} == 'create' && github.ref_name == github.event.repository.default_branch
        working-directory: ./${{ inputs.AWS_service }}/${{ inputs.Infra_env }}
        run: |

            sh "terraform apply -auto-approve"                 
